version: '3.9'

x-base_service: &base_service
    ports:
      - "7860:7860"
    volumes:
      - &v1 ./cache:/cache
      - &v2 ./output:/output
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

name: webui-docker

services:
  download:
    build:
      context: ./services/download/
      args:
        - NO_PROXY=$NO_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - HTTP_PROXY=$HTTP_PROXY
    profiles: ["download"]
    volumes:
      - *v1

  hlky:
    <<: *base_service
    profiles: ["hlky"]
    build: ./services/hlky/
    environment:
      - CLI_ARGS=--optimized-turbo

  automatic1111: &automatic
    <<: *base_service
    profiles: ["auto"]
    build:
      context: ./services/AUTOMATIC1111
      args:
        - NO_PROXY=localhost
        - HTTPS_PROXY=$HTTPS_PROXY
        - HTTP_PROXY=$HTTP_PROXY
    volumes:
      - *v1
      - *v2
      - ./services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
    environment:
      - CLI_ARGS=--allow-code --lowvram
      - HTTPS_PROXY=$HTTPS_PROXY
      - HTTP_PROXY=$HTTP_PROXY
      - NO_PROXY=localhost

  automatic1111-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--allow-code --no-half --precision full
      - HTTPS_PROXY=$HTTPS_PROXY
      - HTTP_PROXY=$HTTP_PROXY
      - NO_PROXY=localhost

  lstein:
    <<: *base_service
    profiles: ["lstein"]
    build: ./services/lstein/
    environment:
      - PRELOAD=false
      - CLI_ARGS=
